### ISSUE TITLE
Mapbox token

### ISSUE THREAD

**Issue by jbelien** [EqualStreetNames/equalstreetnames-luxembourg#1]
@EqualStreetNames/luxembourg Could you update the [`MAPBOX_TOKEN` secret](https://github.com/EqualStreetNames/equalstreetnames-luxembourg/settings/secrets/actions/MAPBOX_TOKEN) used in this repository with a token you provide ?

Open Knowledge Belgium provides a token (if there is no maintainer) but since @DavidMoraisFerreira has joined the party, you need your own token.

Thanks :)

**Comment by DavidMoraisFerreira** [comment]
Done, thank you for the reminder :)
